### ISSUE TITLE
Support for ZoneID

### ISSUE THREAD

**Issue by vchokshi** [jpmens/ansible-m-dnsupdate#3]
Now that AWS has public and private zones, I think dnsupdate needs to ask for the ZoneID, else it updates the public zone (or possibly the first zone it finds).

I am new to git and was going to try to fork this code and fix this problem if you guys can guide me understand where the fix needs to go. I read through this code and was not sure if this is problem that needs to be fixed upstream first in the AWS CLI.

Thanks,
Vihar

**Comment by jpmens** [comment]
What exactly does the AWS CLI have to do with RFC 2136 DNS updates? If you could enlighten me, please, I may be able to assist.

**Comment by vchokshi** [comment]
Oh I'm terribly sorry. The route53 module in ansible is the one that needs updating and I confused it with this repo.

My apologies!
Vihar
